/* Generated by Tools/generate_rules.py. Do not edit directly. */
(function () {
  "use strict";
  globalThis.YNCH_CONFIG = Object.freeze({
  "supportedHosts": [
    "yahoo.co.jp",
    "www.yahoo.co.jp",
    "m.yahoo.co.jp",
    "news.yahoo.co.jp"
  ],
  "keywordScopes": [
    "#newsFeed",
    ".newsFeed_list",
    "[id^='ualmods-newsfeed']",
    "#uamods-recommend",
    "#uamods-also_read",
    "#articleCommentModule",
    "#accr",
    "#cmtr",
    "#swipeFrame",
    "#Topics",
    "[id^='tabpanelTopics']",
    "[id^='tab-panel-']",
    "#topicsList",
    "#comModule"
  ],
  "keywordCards": [
    "#newsFeed > .newsFeed_list > *",
    ".newsFeed_list > *",
    "#newsFeed > ul > li",
    "[data-ual-view-type='list']",
    "#Topics [role='tabpanel'] article",
    "[id^='tabpanelTopics'] article",
    "#uamods-recommend li",
    "#uamods-also_read li",
    "#articleCommentModule [data-ual-view-type='list']",
    "#accr li",
    "#cmtr li",
    "#tab-panel-major .sc-tk5e5f-0.iufzBy",
    "#tab-panel-major .sc-vx8jxp-0.BVmGo",
    "#tab-panel-major .sc-1rk2e3m-0.gEPWPh",
    "#tab-panel-domestic .sc-16x2gvk-0.kDFwkd",
    "#tab-panel-entertainment .sc-16x2gvk-0.kDFwkd",
    "[id^='tab-panel-'] li",
    "[id^='tab-panel-'] article",
    "#topicsList li",
    "#topicsList article",
    "#comModule li"
  ],
  "keywordArticleLinks": [
    "a[href*='news.yahoo.co.jp/articles/']",
    "a[href*='news.yahoo.co.jp/pickup/']",
    "a[href^='/articles/']",
    "a[href^='/pickup/']",
    "a[href*='/articles/']",
    "a[href*='/pickup/']"
  ],
  "keywordHeadlines": [
    "a[href*='/articles/']",
    "a[href*='/pickup/']",
    "[data-cl-params*='_cl_link:title' i]",
    "[data-cl-params*='_cl_vmodule:tpc_' i]",
    "h1",
    "h2",
    "h3",
    "h4",
    "[role='heading']",
    "[itemprop='headline']"
  ]
});
}());
