#!/usr/bin/env python3
import argparse
import difflib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Shared" / "rules.json"


def load_rules():
    with SOURCE.open(encoding="utf-8") as handle:
        return json.load(handle)


def selector_block(selectors, declarations, prefix="", suffix=""):
    lines = []
    for index, selector in enumerate(selectors):
        comma = "," if index < len(selectors) - 1 else " {"
        lines.append(f"{prefix}{selector}{suffix}{comma}")
    lines.extend(f"    {item}" for item in declarations)
    lines.append("}")
    return "\n".join(lines)


def chunks(items, size):
    for index in range(0, len(items), size):
        yield items[index:index + size]


def regex_for_tokens(domain, tokens):
    escaped_domain = re.escape(domain)
    escaped_tokens = "|".join(re.escape(token) for token in tokens)
    return f"^https?://{escaped_domain}/.*({escaped_tokens})"


def generate_static_css(rules):
    body = selector_block(
        rules["staticHideSelectors"],
        ["display: none !important;", "visibility: hidden !important;"],
    )
    return (
        "/* Generated by Tools/generate_rules.py. Do not edit directly. */\n"
        "/* Static selector-based hiding handled by Safari before content.js work. */\n"
        f"{body}\n"
    )


def generate_mobile_css(rules):
    body = selector_block(
        rules["mobileYahooHideSelectors"],
        ["display: none !important;", "visibility: hidden !important;"],
    )
    return (
        "/* Generated by Tools/generate_rules.py. Do not edit directly. */\n"
        "/* Static selector-based hiding for m.yahoo.co.jp only. */\n"
        f"{body}\n"
    )


def generate_content_css(rules):
    hidden = selector_block(
        ["html body [data-keyword-hidden=\"true\"]", "html body .ynch-keyword-hidden"],
        ["display: none !important;", "visibility: hidden !important;"],
    )
    macos = selector_block(
        rules["macOSHideSelectors"],
        ["display: none !important;", "visibility: hidden !important;"],
        prefix="html.ynch-platform-macos ",
    )
    comment = selector_block(
        [".ynch-comment-tab-hidden"],
        ["display: none !important;", "visibility: hidden !important;"],
    )
    active = selector_block(
        rules["keywordCards"],
        ["visibility: hidden !important;"],
        prefix="html.ynch-keyword-filter-active body ",
        suffix=":not([data-keyword-checked=\"true\"])",
    )
    ready = selector_block(
        rules["keywordPendingScopes"],
        ["animation: ynchKeywordReadyFallback 5s steps(1, end) forwards;", "visibility: hidden;"],
        prefix="html:not(.ynch-keyword-filter-ready) body ",
    )
    pending = selector_block(
        rules["keywordPendingScopes"],
        ["visibility: hidden !important;"],
        prefix="html.ynch-keyword-filter-pending body ",
    )
    return "\n\n".join([
        "/* Generated by Tools/generate_rules.py. Do not edit directly. */",
        hidden,
        macos,
        comment,
        active,
        "@keyframes ynchKeywordReadyFallback {\n    to {\n        visibility: visible;\n    }\n}",
        ready,
        pending,
    ]) + "\n"


def generate_network_rules(rules):
    domain = rules["networkBlock"]["domains"][0]
    return json.dumps([
        {
            "id": 1,
            "priority": 1,
            "action": {"type": "block"},
            "condition": {
                "regexFilter": regex_for_tokens(domain, rules["networkBlock"]["tokens"]),
                "resourceTypes": [
                    "sub_frame",
                    "stylesheet",
                    "script",
                    "image",
                    "font",
                    "xmlhttprequest",
                    "ping",
                    "media",
                    "websocket",
                    "other",
                ],
            },
        }
    ], ensure_ascii=False, indent=2) + "\n"


def generate_content_blocker(rules):
    network = rules["networkBlock"]
    domain = network["domains"][0]
    output = [
        {
            "trigger": {
                "url-filter": regex_for_tokens(domain, network["tokens"]),
                "if-domain": network["domains"],
                "resource-type": [
                    "image",
                    "style-sheet",
                    "script",
                    "font",
                    "raw",
                    "media",
                    "svg-document",
                ],
            },
            "action": {"type": "block"},
        }
    ]

    for group in chunks(rules["staticHideSelectors"], 5):
        output.append({
            "trigger": {
                "url-filter": ".*",
                "if-domain": rules["supportedHosts"],
            },
            "action": {
                "type": "css-display-none",
                "selector": ", ".join(group),
            },
        })

    output.append({
        "trigger": {
            "url-filter": ".*",
            "if-domain": ["m.yahoo.co.jp"],
        },
        "action": {
            "type": "css-display-none",
            "selector": ", ".join(rules["mobileYahooHideSelectors"]),
        },
    })
    return json.dumps(output, ensure_ascii=False, indent=2) + "\n"


def generate_config_js(rules):
    config = {
        "supportedHosts": rules["supportedHosts"],
        "keywordScopes": rules["keywordScopes"],
        "keywordCards": rules["keywordCards"],
        "keywordArticleLinks": rules["keywordArticleLinks"],
        "keywordHeadlines": rules["keywordHeadlines"],
    }
    payload = json.dumps(config, ensure_ascii=False, indent=2)
    return (
        "/* Generated by Tools/generate_rules.py. Do not edit directly. */\n"
        "(function () {\n"
        "  \"use strict\";\n"
        f"  globalThis.YNCH_CONFIG = Object.freeze({payload});\n"
        "}());\n"
    )


def generated_files(rules):
    return {
        ROOT / "Extension" / "Resources" / "static_rules.css": generate_static_css(rules),
        ROOT / "Extension" / "Resources" / "static_rules_m_yahoo.css": generate_mobile_css(rules),
        ROOT / "Extension" / "Resources" / "content.css": generate_content_css(rules),
        ROOT / "Extension" / "Resources" / "network_rules.json": generate_network_rules(rules),
        ROOT / "ContentBlocker" / "blockerList.json": generate_content_blocker(rules),
        ROOT / "Extension" / "Resources" / "generated_config.js": generate_config_js(rules),
    }


def check_file(path, expected):
    if not path.exists():
        return [f"{path.relative_to(ROOT)} is missing"]
    current = path.read_text(encoding="utf-8")
    if current == expected:
        return []
    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(ROOT)),
        tofile=f"{path.relative_to(ROOT)} (generated)",
        lineterm="",
    )
    return ["\n".join(diff)]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    rules = load_rules()
    files = generated_files(rules)
    if args.check:
        failures = []
        for path, expected in files.items():
            failures.extend(check_file(path, expected))
        if failures:
            print("\n\n".join(failures), file=sys.stderr)
            return 1
        return 0

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
